name: Build docs from help

on:
  workflow_dispatch: # Allow manual trigger
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  generate:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      # We still need to install pywin32 because
      # AutoDuck/py2d.py currently relies on runtime imports for introspection
      # Downloading latest release is faster than re-building
      - name: Install latest release
        run: pip install --user --upgrade pywin32
      - name: Generate PyWin32.chm help file
        run: python AutoDuck/make.py
      - name: Decompile help file into HTML
        run: hh -decompile site PyWin32.chm
      - name: Rename root HTML file
        run: mv site\PyWin32.HTML site\index.html
      - uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: site/

  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published' || github.event_name == 'workflow_dispatch'
    needs:
      - generate
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: documentation
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          commit_message: ${{ github.event.head_commit.message }}
